// 1) Unbounded probabilistic reachability
<<p1:p2>>max=? ( P[F s=1] + P[F s=2] )

// 2) Bounded probabilistic reachability
<<p1:p2>>max=? ( P[F<=k s=1] + P[F<=k s=2] )

// 3) Bounded cumulative rewards
const int k=2;
<<p1:p2>>max=? ( R{"r1"}[C<=k] + R{"r2"}[C<=k] )

// 4) Unbounded reachability reward
<<p1:p2>>min=? ( R{"r1"}[F s=2] + R{"r2"}[F s=1] )

// maximum probability of reaching s1
<<p1>> Pmax=? [ F s=1 ]

<<p1>> Pmax=? [ F<=k (s=1)]