#!/usr/bin/env python3
"""
Generate parameterized scaling families of the Safe-vs-Risky CSG for the
|S| and |A| scaling experiments (rebuttal E3).

PRISM's modelling language cannot express distributions over a parameterized
number of successors, so the family members are generated as concrete .prism
files. Run from this directory:

    python3 generate_models.py

|S| family (safe_risky_states_N<c>.prism, c = channels per joint action):
  A "hub" generalization: each joint action at the start state leads uniformly
  to its own set of c intermediate "channel" states; each channel then plays
  out (a jittered copy of) the original outcome distribution of that joint
  action. Channel-level jitter (+/-0.05, zero-sum within each group) makes the
  channels distinct learning targets while preserving the original game values,
  equilibrium structure, and the fixed property horizon (k=3). |S| = 4c + 4.

|A| family (safe_risky_actions_m<m>.prism, m = actions per player):
  m actions per player (m^2 joint actions) at the start state. Action 1 is
  "risky" (diagonal (1,1): 0.9 high / 0.1 trap), actions i >= 2 are "safe"
  variants (diagonal (i,i): p_i high / 1-p_i medium with p_i = 0.6 - 0.05(i-2)),
  and mismatched joint actions give 0.5 high / 0.5 trap. m=2 recovers the
  original Safe-vs-Risky game. |S| = 4 fixed.

Both families share label-based properties (safe_risky_states.props /
safe_risky_actions.props): the original bounded reachability objective
  <<p1:p2>>max=? ( P[F<=3 "high"] + P[F<=3 "medium"] )
"""

import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

STATES_FAMILY_CHANNELS = [1, 2, 4, 8, 14]   # |S| = 8, 12, 20, 36, 60
ACTIONS_FAMILY_M = [1, 2, 3, 4, 5, 6, 7, 8]   # |A| = 1, 4, 9, 16, 25, 36, 49, 64

PROP = '<<p1:p2>>max=? ( P[F<=3 "high"] + P[F<=3 "medium"] )\n'


def jitters(c):
    """Zero-sum jitter sequence of length c: +0.05/-0.05 pairs, final 0 if odd."""
    js = []
    for t in range(c):
        if c % 2 == 1 and t == c - 1:
            js.append(0.0)
        else:
            js.append(0.05 if t % 2 == 0 else -0.05)
    assert abs(sum(js)) < 1e-12
    return js


def fmt(p):
    return ("%.10f" % p).rstrip("0").rstrip(".")


def gen_states_model(c):
    """Hub variant with c channels per joint action."""
    # state layout: 0 = start; 1..4c = channels (4 groups of c); then high, medium, trap
    high = 4 * c + 1
    medium = 4 * c + 2
    trap = 4 * c + 3
    smax = trap

    # per-joint-action outcome templates: (p_high, p_medium, p_trap)
    # risky (a1,a2): 0.9 high / 0.1 trap; mismatches: 0.5 high / 0.5 trap;
    # safe (b1,b2): 0.6 high / 0.4 medium  (matching the original game)
    groups = [
        ("[a1,a2]", 0.9, 0.0),   # (p_high, p_medium); trap = remainder
        ("[a1,b2]", 0.5, 0.0),
        ("[b1,a2]", 0.5, 0.0),
        ("[b1,b2]", 0.6, 0.4),
    ]

    lines = []
    lines.append("csg")
    lines.append("")
    lines.append("// Generated by generate_models.py -- |S| scaling family (hub variant of Safe vs Risky)")
    lines.append("// c = %d channels per joint action; |S| = %d" % (c, smax + 1))
    lines.append("")
    lines.append("player p1 m1 endplayer")
    lines.append("player p2 m2 endplayer")
    lines.append("")
    lines.append("module m1")
    lines.append("    [a1] true -> true;")
    lines.append("    [b1] true -> true;")
    lines.append("endmodule")
    lines.append("")
    lines.append("module m2 = m1[a1=a2,b1=b2] endmodule")
    lines.append("")
    lines.append("module game")
    lines.append("    s : [0..%d] init 0; // 0 start; 1..%d channels; %d high, %d medium, %d trap"
                 % (smax, 4 * c, high, medium, trap))
    lines.append("")
    # joint actions: uniform over own channel group
    for g, (act, _, _) in enumerate(groups):
        first = g * c + 1
        terms = " + ".join("1/%d:(s'=%d)" % (c, first + t) for t in range(c))
        lines.append("    %s s=0 -> %s;" % (act, terms))
    lines.append("")
    # channels: jittered copy of the group's outcome distribution
    for g, (act, ph, pm) in enumerate(groups):
        js = jitters(c)
        for t in range(c):
            ch = g * c + 1 + t
            # jitter shifts mass between high and the group's other outcome
            # (medium for the safe group, trap otherwise), keeping a valid distribution
            p_high = ph + js[t]
            p_med = pm - js[t] if pm > 0 else 0.0
            p_trap = 1.0 - p_high - p_med
            assert -1e-12 <= p_trap <= 1.0 and 0.0 <= p_high <= 1.0 and 0.0 <= p_med <= 1.0
            p_trap = max(p_trap, 0.0)
            terms = []
            if p_high > 1e-12:
                terms.append("%s:(s'=%d)" % (fmt(p_high), high))
            if p_med > 1e-12:
                terms.append("%s:(s'=%d)" % (fmt(p_med), medium))
            if p_trap > 1e-12:
                terms.append("%s:(s'=%d)" % (fmt(p_trap), trap))
            lines.append("    [] s=%d -> %s; // channel for %s" % (ch, " + ".join(terms), act))
    lines.append("")
    lines.append("    [] s>=%d -> (s'=s); // absorbing" % high)
    lines.append("endmodule")
    lines.append("")
    lines.append('label "high" = s=%d;' % high)
    lines.append('label "medium" = s=%d;' % medium)
    lines.append("")
    for r in ("r1", "r2"):
        lines.append('rewards "%s"' % r)
        lines.append("    s=%d : 1;" % high)
        lines.append("    s=%d : 0.6;" % medium)
        lines.append("endrewards")
        lines.append("")
    return "\n".join(lines)


def gen_actions_model(m):
    """m actions per player at the start state (m^2 joint actions)."""
    lines = []
    lines.append("csg")
    lines.append("")
    lines.append("// Generated by generate_models.py -- |A| scaling family of Safe vs Risky")
    lines.append("// m = %d actions per player; |A| = %d joint actions; |S| = 4" % (m, m * m))
    lines.append("")
    lines.append("player p1 m1 endplayer")
    lines.append("player p2 m2 endplayer")
    lines.append("")
    lines.append("module m1")
    for i in range(1, m + 1):
        lines.append("    [x1_%d] true -> true;" % i)
    lines.append("endmodule")
    lines.append("")
    renames = ",".join("x1_%d=x2_%d" % (i, i) for i in range(1, m + 1))
    lines.append("module m2 = m1[%s] endmodule" % renames)
    lines.append("")
    lines.append("module game")
    lines.append("    s : [0..3] init 0; // 0 start, 1 high, 2 medium, 3 trap")
    lines.append("")
    for i in range(1, m + 1):
        for j in range(1, m + 1):
            act = "[x1_%d,x2_%d]" % (i, j)
            if i == j == 1:
                dist = "0.9:(s'=1) + 0.1:(s'=3)"  # risky coordination
            elif i == j:
                ph = 0.6 - 0.05 * (i - 2)        # safe variants
                dist = "%s:(s'=1) + %s:(s'=2)" % (fmt(ph), fmt(1.0 - ph))
            else:
                dist = "0.5:(s'=1) + 0.5:(s'=3)"  # miscoordination
            lines.append("    %s s=0 -> %s;" % (act, dist))
    lines.append("")
    lines.append("    [] s>0 -> (s'=s); // absorbing")
    lines.append("endmodule")
    lines.append("")
    lines.append('label "high" = s=1;')
    lines.append('label "medium" = s=2;')
    lines.append("")
    for r in ("r1", "r2"):
        lines.append('rewards "%s"' % r)
        lines.append("    s=1 : 1;")
        lines.append("    s=2 : 0.6;")
        lines.append("endrewards")
        lines.append("")
    return "\n".join(lines)


def write(path, content):
    with open(path, "w") as f:
        f.write(content)
    print("wrote", os.path.relpath(path, OUT_DIR))


def main():
    for c in STATES_FAMILY_CHANNELS:
        write(os.path.join(OUT_DIR, "safe_risky_states_N%d.prism" % c), gen_states_model(c))
    for m in ACTIONS_FAMILY_M:
        write(os.path.join(OUT_DIR, "safe_risky_actions_m%d.prism" % m), gen_actions_model(m))
    header = "// bounded reachability objective (fixed horizon k=3); labels defined in the model files\n"
    write(os.path.join(OUT_DIR, "safe_risky_states.props"), header + PROP)
    write(os.path.join(OUT_DIR, "safe_risky_actions.props"), header + PROP)


if __name__ == "__main__":
    main()
